package seed

import (
	"fmt"
	"math/rand/v2"
	mysqs "yoink/utils/myaws/sqs"

	"github.com/aws/aws-sdk-go-v2/aws"
)

// creating a seed url list out of all famous llms lol for additional diversity
func SeedSQS(){
	
	var SeedURLs = []string{
		// gemini
		// 1. Science, Space & Nature
		"https://www.nasa.gov",
		"https://arxiv.org",
		"https://www.nature.com",
		"https://www.allaboutbirds.org",
		"https://www.windy.com",
		"https://www.marinetraffic.com",
		"https://www.space-track.org",
		"https://bugguide.net",
		"https://www.volcanodiscovery.com",
		"https://deepseanews.com",
		"https://www.inaturalist.org",
		"https://www.amnh.org",
		"https://www.palomar.edu",

		// 2. History, Philosophy & Literature
		"https://www.gutenberg.org",
		"https://plato.stanford.edu",
		"https://www.loc.gov",
		"https://www.sacred-texts.com",
		"https://www.poetryfoundation.org",
		"https://www.perseus.tufts.edu",
		"https://www.historians.org",
		"https://www.oldbaileyonline.org",
		"https://www.marxists.org",
		"https://www.bl.uk",
		"https://www.laphamsquarterly.org",
		"https://www.epistemeic.com",

		// 3. Arts, Culture & Design
		"https://www.louvre.fr/en",
		"https://www.behance.net",
		"https://www.artstation.com",
		"https://www.moma.org",
		"https://www.fontsinuse.com",
		"https://www.archdaily.com",
		"https://www.ubu.com",
		"https://www.colossal.com",
		"https://www.openculture.com",
		"https://www.film-foundation.org",
		"https://www.hyperallergic.com",
		"https://www.streetartbio.com",

		// 4. Tech, Software & Infrastructure
		"https://github.com",
		"https://news.ycombinator.com",
		"https://www.w3.org",
		"https://www.rfc-editor.org",
		"https://www.shodan.io",
		"https://www.kernel.org",
		"https://www.hackaday.com",
		"https://www.lowendtalk.com",
		"https://www.phrack.org",
		"https://textboard.org",
		"https://www.osnews.com",
		"https://www.packetstormsecurity.com",

		// 5. Public Reference, Geospatial & Data
		"https://www.wikipedia.org",
		"https://www.openstreetmap.org",
		"https://www.cia.gov",
		"https://www.gsa.gov",
		"https://www.geonames.org",
		"https://www.data.gov",
		"https://www.worldometers.info",
		"https://www.imf.org",
		"https://www.un.org",
		"https://www.ncdc.noaa.gov",
		"https://www.fao.org",
		"https://www.who.int",

		// 6. Lifestyle, Hobbies & Crafting
		"https://www.ifixit.com",
		"https://www.boardgamegeek.com",
		"https://www.seriouseats.com",
		"https://www.head-fi.org",
		"https://www.ravelry.com",
		"https://www.alltrails.com",
		"https://www.discogs.com",
		"https://www.fountainpennetwork.com",
		"https://www.hermitary.com",
		"https://www.shroomery.org",
		"https://www.goodreads.com",
		"https://www.spriters-resource.com",

		// 7. Economy, Finance & Markets
		"https://www.bloomberg.com",
		"https://www.ft.com",
		"https://www.investopedia.com",
		"https://www.morningstar.com",
		"https://www.bis.org",
		"https://www.visualcapitalist.com",
		"https://www.coingecko.com",
		"https://www.sec.gov",
		"https://www.scrimshaw.com",
		"https://www.treasury.gov",
		"https://www.mises.org",
		"https://www.maritime-executive.com",

		// 8. Unconventional, Retro & Internet Artifacts
		"https://neocities.org",
		"https://www.wunderkammer.com",
		"https://www.textfiles.com",
		"https://www.scpwiki.com",
		"https://www.smallsound.org",
		"https://www.abandonwaredos.com",
		"https://www.atlasobscura.com",
		"https://www.zombo.com",
		"https://www.cameratrons.com",
		"https://www.supercook.com",
		"https://www.radio-electronics.com",
		"https://www.billiondollarprint.com",
		"https://www.vintagesynth.com",
		"https://www.forgottenbooks.com",
		"https://archive.org", // Added the Internet Archive to round out the 100 perfectly!

		// deepseek
		// General Knowledge & Learning
		"https://www.britannica.com",
		"https://www.projectgutenberg.org",
		"https://www.smithsonianmag.com",
		"https://www.atlasobscura.com",
		"https://www.mentalfloss.com",
		"https://www.omniglot.com",
		"https://www.worldatlas.com",
		"https://www.nationalgeographic.com",
		"https://www.khanacademy.org",
		"https://www.duolingo.com",

		// Tech & Programming
		"https://www.dev.to",
		"https://www.smashingmagazine.com",
		"https://www.alistapart.com",
		"https://www.codeproject.com",
		"https://www.daily.dev",
		"https://www.techcrunch.com",
		"https://www.wired.com",
		"https://www.arduino.cc",
		"https://www.raspberrypi.org",
		"https://www.python.org",

		// News & World Affairs
		"https://www.reuters.com",
		"https://www.aljazeera.com",
		"https://www.bbc.com",
		"https://www.npr.org",
		"https://www.theatlantic.com",
		"https://www.economist.com",
		"https://www.france24.com",
		"https://www.dw.com",
		"https://www.scmp.com",
		"https://www.foreignaffairs.com",

		// Art, Design & Culture
		"https://www.behance.net",
		"https://www.deviantart.com",
		"https://www.artsy.net",
		"https://www.moma.org",
		"https://www.louvre.fr",
		"https://www.metmuseum.org",
		"https://www.britishmuseum.org",
		"https://www.guggenheim.org",
		"https://www.tate.org.uk",
		"https://www.getty.edu",

		// Health & Science
		"https://www.mayoclinic.org",
		"https://www.webmd.com",
		"https://www.nih.gov",
		"https://www.who.int",
		"https://www.cdc.gov",
		"https://www.nature.com",
		"https://www.scientificamerican.com",
		"https://www.livescience.com",
		"https://www.space.com",
		"https://www.nasa.gov",

		// Finance & Business
		"https://www.bloomberg.com",
		"https://www.cnbc.com",
		"https://www.ft.com",
		"https://www.wsj.com",
		"https://www.investopedia.com",
		"https://www.forbes.com",
		"https://www.businessinsider.com",
		"https://www.morningstar.com",
		"https://www.fool.com",
		"https://www.coindesk.com",

		// Entertainment & Gaming
		"https://www.ign.com",
		"https://www.gamespot.com",
		"https://www.polygon.com",
		"https://www.eurogamer.net",
		"https://www.giantbomb.com",
		"https://www.twitch.tv",
		"https://www.steampowered.com",
		"https://www.gog.com",
		"https://www.rockpapershotgun.com",
		"https://www.kotaku.com",

		// Literature & Writing
		"https://www.goodreads.com",
		"https://www.poetryfoundation.org",
		"https://www.wattpad.com",
		"https://www.medium.com",
		"https://www.scribd.com",
		"https://www.theguardian.com/books",
		"https://www.nytimes.com/books",
		"https://www.literaryhub.com",
		"https://www.bookbub.com",
		"https://www.writersdigest.com",

		// Lifestyle & Hobbies
		"https://www.wikihow.com",
		"https://www.instructables.com",
		"https://www.allrecipes.com",
		"https://www.seriouseats.com",
		"https://www.thespruce.com",
		"https://www.gardenersworld.com",
		"https://www.houzz.com",
		"https://www.apartmenttherapy.com",
		"https://www.boardgamegeek.com",
		"https://www.geocaching.com",

		// Government & Institutions
		"https://www.whitehouse.gov",
		"https://www.un.org",
		"https://www.ec.europa.eu",
		"https://www.wto.org",
		"https://www.imf.org",
		"https://www.worldbank.org",
		"https://www.redcross.org",
		"https://www.amnesty.org",
		"https://www.greenpeace.org",
		"https://www.wikileaks.org",

		// Bonus - Weird & Obscure
		"https://www.boredpanda.com",
		"https://www.damninteresting.com",
		"https://www.theregister.com",
		"https://www.futurism.com",

		// grok
		// SeedURLs contains a diverse set of starting URLs for the crawler
		"https://www.wikipedia.org/",
		"https://www.bbc.com/",
		"https://www.nytimes.com/",
		"https://www.reddit.com/",
		"https://news.ycombinator.com/",
		"https://www.theguardian.com/",
		"https://www.cnn.com/",
		"https://www.amazon.com/",
		"https://www.youtube.com/",
		"https://x.com/",
		"https://www.facebook.com/",
		"https://www.instagram.com/",
		"https://www.linkedin.com/",
		"https://www.ebay.com/",
		"https://www.nih.gov/",
		"https://www.who.int/",
		"https://www.nasa.gov/",
		"https://www.imdb.com/",
		"https://www.wsj.com/",
		"https://www.forbes.com/",

		"https://www.reuters.com/",
		"https://apnews.com/",
		"https://www.aljazeera.com/",
		"https://www.usnews.com/",
		"https://www.whitehouse.gov/",
		"https://www.gov.uk/",
		"https://www.canada.ca/",
		"https://www.europa.eu/",
		"https://www.un.org/",
		"https://www.cia.gov/the-world-factbook/",
		"https://www.state.gov/",
		"https://www.bbc.co.uk/news",
		"https://www.theverge.com/",
		"https://arstechnica.com/",
		"https://www.wired.com/",

		"https://www.khanacademy.org/",
		"https://ocw.mit.edu/",
		"https://www.coursera.org/",
		"https://www.edx.org/",
		"https://www.britannica.com/",
		"https://www.smithsonianmag.com/",
		"https://www.nature.com/",
		"https://www.science.org/",
		"https://arxiv.org/",
		"https://www.jstor.org/",

		"https://www.scientificamerican.com/",
		"https://www.popsci.com/",
		"https://www.howstuffworks.com/",
		"https://www.quantamagazine.org/",
		"https://www.edge.org/",
		"https://www.noaa.gov/",
		"https://www.epa.gov/",
		"https://www.worldwildlife.org/",
		"https://commoncrawl.org/",

		"https://www.mayoclinic.org/",
		"https://www.webmd.com/",
		"https://www.healthline.com/",
		"https://www.cdc.gov/",
		"https://www.medicalnewstoday.com/",
		"https://www.strava.com/",
		"https://www.myfitnesspal.com/",
		"https://www.headspace.com/",
		"https://www.psychologytoday.com/",
		"https://www.apha.org/",

		"https://www.lonelyplanet.com/",
		"https://www.tripadvisor.com/",
		"https://www.atlasobscura.com/",
		"https://www.allrecipes.com/",
		"https://www.bbcgoodfood.com/",
		"https://www.seriouseats.com/",
		"https://www.nationalgeographic.com/travel",
		"https://www.roughguides.com/",
		"https://www.cntraveler.com/",
		"https://www.timeout.com/",
		"https://www.eater.com/",
		"https://www.thekitchn.com/",
		"https://www.nomadicmatt.com/",
		"https://www.the-savvy-backpacker.com/",
		"https://www.afar.com/",

		"https://www.metmuseum.org/",
		"https://www.moma.org/",
		"https://www.rollingstone.com/",
		"https://pitchfork.com/",
		"https://www.goodreads.com/",
		"https://www.artsy.net/",
		"https://www.deviantart.com/",
		"https://www.archive.org/",
		"https://www.thisman.org/",
		"https://pointerpointer.com/",

		"https://www.investopedia.com/",
		"https://www.bloomberg.com/",
		"https://www.etsy.com/",
		"https://news.ycombinator.com/",
		"https://www.producthunt.com/",
		"https://neal.fun/",
		"https://theuselessweb.com/",
		"https://cloudhiker.net/",
		"https://www.milliondollarhomepage.com/",
		"https://wikiroulette.co/",

		// perplexity
		"https://www.wikipedia.org",
		"https://www.google.com",
		"https://www.youtube.com",
		"https://www.facebook.com",
		"https://www.twitter.com",
		"https://www.reddit.com",
		"https://www.instagram.com",
		"https://www.linkedin.com",
		"https://www.wikipedia.org/wiki/Main_Page",
		"https://www.nytimes.com",
		"https://www.theguardian.com",
		"https://www.bbc.com/news",
		"https://www.reuters.com",
		"https://www.washingtonpost.com",
		"https://www.aljazeera.com",
		"https://www.bloomberg.com",
		"https://www.forbes.com",
		"https://www.wsj.com",
		"https://www.axios.com",
		"https://www.politico.com",
		"https://www.sciencemag.org",
		"https://www.nature.com",
		"https://www.pnas.org",
		"https://www.ncbi.nlm.nih.gov",
		"https://www.arxiv.org",
		"https://www.nasa.gov",
		"https://www.esa.int",
		"https://home.cern",
		"https://www.who.int",
		"https://www.un.org",
		"https://www.gov.uk",
		"https://www.whitehouse.gov",
		"https://www.parliament.uk",
		"https://www.congress.gov",
		"https://www.euronews.com",
		"https://www.dw.com",
		"https://www.france24.com",
		"https://www.cnn.com",
		"https://www.foxnews.com",
		"https://www.espn.com",
		"https://www.bbc.com/sport",
		"https://olympics.com",
		"https://www.fifa.com",
		"https://www.nba.com",
		"https://www.rollingstone.com",
		"https://www.nme.com",
		"https://pitchfork.com",
		"https://www.artnet.com",
		"https://www.tate.org.uk",
		"https://www.metmuseum.org",
		"https://www.vam.ac.uk",
		"https://www.smithsonianmag.com",
		"https://www.britannica.com",
		"https://stackoverflow.com",
		"https://github.com",
		"https://gitlab.com",
		"https://medium.com",
		"https://substack.com",
		"https://www.kaggle.com",
		"https://www.hackerrank.com",
		"https://codeforces.com",
		"https://www.freecodecamp.org",
		"https://www.w3.org",
		"https://www.mozilla.org",
		"https://www.apache.org",
		"https://www.python.org",
		"https://www.rust-lang.org",
		"https://go.dev",
		"https://www.linux.org",
		"https://www.khanacademy.org",
		"https://www.coursera.org",
		"https://www.edx.org",
		"https://stackexchange.com",
		"https://www.quora.com",
		"https://www.ted.com",
		"https://www.pbs.org",
		"https://www.npr.org",
		"https://archive.org",
		"https://commons.wikimedia.org",
		"https://www.openstreetmap.org",
		"https://www.wikidata.org",
		"https://wikisource.org",
		"https://blog.golang.org",
		"https://www.salon.com",
		"https://www.aclu.org",
		"https://www.amnesty.org",
		"https://www.unicef.org",
		"https://www.redcross.org",
		"https://www.doctorswithoutborders.org",
		"https://www.habitat.org",
		"https://www.eff.org",
		"https://www.propublica.org",
		"https://www.npr.org/sections/technology/",
		"https://www.scientificamerican.com",
		"https://www.roadandtrack.com",
		"https://www.atlasobscura.com",
		"https://longreads.com",
		"https://aeon.co",
		"https://www.brainpickings.org",
		"https://www.openculture.com",
		"https://www.loc.gov",

		// claude
		// News & journalism
		"https://www.bbc.com",
		"https://www.reuters.com",
		"https://apnews.com",
		"https://www.aljazeera.com",
		"https://www.npr.org",
		"https://www.theguardian.com",
		"https://www.propublica.org",

		// Long-form & magazines
		"https://longreads.com",
		"https://narratively.com",
		"https://www.theatlantic.com",
		"https://harpers.org",
		"https://granta.com",
		"https://www.parisreview.org",
		"https://lithub.com",
		"https://www.themarginalian.org",

		// Science & research
		"https://www.quantamagazine.org",
		"https://aeon.co",
		"https://nautil.us",
		"https://www.scientificamerican.com",
		"https://eos.org",
		"https://www.hakaimagazine.com",
		"https://undark.org",
		"https://phys.org",

		// Space
		"https://www.nasa.gov",
		"https://www.esa.int",
		"https://www.planetary.org",
		"https://www.skyandtelescope.org",
		"https://earthsky.org",

		// Nature & environment
		"https://www.audubon.org",
		"https://www.iucn.org",
		"https://e360.yale.org",
		"https://www.mongabay.com",
		"https://www.biographic.com",

		// History & archives
		"https://www.smithsonianmag.com",
		"https://publicdomainreview.org",
		"https://www.gutenberg.org",
		"https://archive.org",
		"https://www.loc.gov",
		"https://www.britishmuseum.org",
		"https://www.historytoday.com",

		// Weird, obscure & trivia
		"https://www.atlasobscura.com",
		"https://www.damninteresting.com",
		"https://www.futilitycloset.com",
		"https://www.todayifoundout.com",
		"https://www.mentalfloss.com",
		"https://99percentinvisible.org",

		// Philosophy & ideas
		"https://plato.stanford.edu",
		"https://iep.utm.edu",
		"https://www.lesswrong.com",
		"https://marginalrevolution.com",
		"https://fs.blog",

		// Economics, finance & data
		"https://www.imf.org",
		"https://ourworldindata.org",
		"https://www.gapminder.org",
		"https://www.visualcapitalist.com",
		"https://fred.stlouisfed.org",
		"https://flowingdata.com",

		// Literature & poetry
		"https://www.poetryfoundation.org",
		"https://wordswithoutborders.org",
		"https://www.mcsweeneys.net",
		"https://www.electricliterature.com",

		// Music
		"https://pitchfork.com",
		"https://daily.bandcamp.com",
		"https://www.allmusic.com",

		// Film & comics
		"https://www.rogerebert.com",
		"https://www.criterion.com",
		"https://www.tcm.com",
		"https://www.cbr.com",

		// Food & drink
		"https://www.seriouseats.com",
		"https://www.thekitchn.com",
		"https://www.eater.com",
		"https://www.beeradvocate.com",
		"https://www.coffeeresearch.org",

		// Travel & geography
		"https://www.lonelyplanet.com",
		"https://www.openstreetmap.org",
		"https://www.nationalgeographic.com",

		// Sports
		"https://www.espn.com",
		"https://www.theathletic.com",
		"https://www.cyclingnews.com",
		"https://www.worldrugby.org",

		// Gaming & tabletop
		"https://www.rockpapershotgun.com",
		"https://www.polygon.com",
		"https://boardgamegeek.com",
		"https://www.dndbeyond.com",

		// Tech & programming
		"https://news.ycombinator.com",
		"https://stackoverflow.com",
		"https://github.com",
		"https://lwn.net",
		"https://hackaday.com",

		// Health & psychology
		"https://www.who.int",
		"https://www.psychologytoday.com",
		"https://www.apa.org",

		// Wikis & reference
		"https://en.wikipedia.org",
		"https://en.wikisource.org",
		"https://en.wiktionary.org",
		"https://tvtropes.org",
		"https://www.etymonline.com",

		// Niche hobbies
		"https://www.finewoodworking.com",
		"https://www.ravelry.com",
		"https://www.mushroomexpert.com",
	}
	mysqs.GetQueueURL()

	rand.Shuffle(len(SeedURLs), func(i, j int) {
		SeedURLs[i], SeedURLs[j] = SeedURLs[j], SeedURLs[i]
	})
	for i, url := range SeedURLs{
		output, err := mysqs.SendMessage(url)
		if err != nil{
			panic(fmt.Errorf("error in sqs send message --- %s", err.Error()))
		}
		fmt.Printf("success - url %d: %v\n", i+1, aws.ToString(output.MD5OfMessageBody))
	}
}